quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/hexarch


quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changeLog.xml
